### ISSUE TITLE
An internal server error occurred

### ISSUE THREAD

**Issue by ghost** [GreenVolume/HumHub-Messenger#6]
I have this error in Overview and some pages. It doesn´t appear in administration for example. My HumHub version is 1.1.1.

Thanks.

**Comment by ghost** [comment]
ERROR  Tue, 13 Dec 2016 10:54:29 +0000  

yii\base\InvalidParamException
exception 'yii\base\InvalidParamException' with message 'The view file does not exist: /home/opengrow/public_html/es/community/protected/modules/HumHub-Messenger-master/widgets/views/ messengerframe.php' in /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/View.php:226 Stack trace: #0 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/opengrow/...', Array, Object(humhub\modules\messenger\widgets\MessengerFrame)) #1 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Widget.php(195): yii\base\View->render(' messengerframe', Array, Object(humhub\modules\messenger\widgets\MessengerFrame)) #2 /home/opengrow/public_html/es/community/protected/modules/HumHub-Messenger-master/widgets/MessengerFrame.php(13): yii\base\Widget->render(' messengerframe', Array) #3 /home/opengrow/public_html/es/community/protected/humhub/components/Widget.php(70): humhub\modules\messenger\widgets\MessengerFrame->run() #4 /home/opengrow/public_html/es/community/protected/humhub/components/Widget.php(52): humhub\components\Widget->process() #5 /home/opengrow/public_html/es/community/protected/humhub/widgets/BaseStack.php(92): humhub\components\Widget::widget(Array) #6 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Widget.php(102): humhub\widgets\BaseStack->run() #7 /home/opengrow/public_html/es/community/protected/humhub/modules/dashboard/views/dashboard/index.php(22): yii\base\Widget::widget(Array) #8 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/View.php(325): require('/home/opengrow/...') #9 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/opengrow/...', Array) #10 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/opengrow/...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #11 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(378): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #12 /home/opengrow/public_html/es/community/protected/humhub/modules/dashboard/controllers/DashboardController.php(64): yii\base\Controller->render('index', Array) #13 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #14 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #15 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #16 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('', Array) #17 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('', Array) #18 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #19 /home/opengrow/public_html/es/community/index.php(25): yii\base\Application->run() #20 {main}

**Comment by Felli** [comment]
This module isn't up to date with the newer versions of Humhub, would be best not to use.
